---

- name: apt check updates
  apt:
    update_cache: yes

- name: apt list upgradable
  shell:
    cmd: apt list --upgradable
  register: output
  changed_when: output.stdout_lines | length > 1

- name: apt show availables updates
  debug:
    msg:  "\
          {% set output2 = [] %}\
            {% for line in output.stdout_lines %}\
              {% if line != 'Listing...' %}\
                {{ output2.append( line ) }}\
              {% endif %}\
            {% endfor %}\
          {{ output2 }}\
          "
  when: >
        output.stdout_lines is defined
        and
        output.stdout_lines | length > 1
