---
- name: Apt check updates
  ansible.builtin.apt:
    update_cache: true

- name: Apt list upgradable
  register: output
  changed_when: output.stdout_lines | length > 1
  ansible.builtin.shell:
    cmd: apt list --upgradable

- name: Apt show availables updates
  when:
    - output.stdout_lines is defined
    - output.stdout_lines | length > 1
  ansible.builtin.debug:
    msg: "\
      {% set output2 = [] %}\
      {% for line in output.stdout_lines %}\
      {% if line != 'Listing...' or line != 'En train de lister...' %}\
      {{ output2.append(line) }}\
      {% endif %}\
      {% endfor %}\
      {{ output2 }}\
      "
