---
- name: Dnf check updates
  ansible.builtin.dnf:
    list: updates
    update_cache: true
  register: output

- name: Dnf show availables updates
  ansible.builtin.debug:
    msg: "\
      {% set output2 = [] %}\
      {% for pkg in output.results %}\
      {{ output2.append( pkg.name ~ '-' ~ pkg.version ) }}\
      {% endfor %}\
      {{ output2 }}\
      "
  when: >
    output.results is defined
    and
    output.results is iterable
    and
    output.results | length > 0
