---
# - name: install/remove with apt
#   ansible.builtin.apt:
#     name: "{{ item.apt | default(item.name) }}"
#     state: "{{ item.state | default(package_state) }}"
#     update_cache: "{{ packages_update_cache }}"
#     # cache_valid_time: "{{ package_cache_valid_time }}"
#     # install_recommends: "{{ item.apt_install_recommends | default(omit) }}"
#   when: ( item.apt_ignore | default('no') ) | string in 'False,false,No,no'
#   with_items: "{{ packages_list }}"


- name: Apt init removal packages list
  ansible.builtin.set_fact:
    list_remove: []

- name: Apt  populate removal packages list
  when:
    - ( item.apt_ignore | default('no') ) | string in 'False,false,No,no'
    - item.state | default(package_state) == "absent"
  with_items: "{{ packages_list }}"
  ansible.builtin.set_fact:
    list_remove: "{{ list_remove + [item.apt | default(item.name)] }}"

- name: Apt remove packages
  when: 
    - list_remove is defined
    - list_remove | length > 0
  ansible.builtin.apt:
    name: "{{ list_remove }}"
    state: "absent"


- name: Apt init install packages list
  ansible.builtin.set_fact:
    list_add: []

- name: Apt populate install packages list
  when:
    - ( item.apt_ignore | default('no') ) | string in 'False,false,No,no'
    - item.state | default(package_state) == "present"
  with_items: "{{ packages_list }}"
  ansible.builtin.set_fact:
    list_add: "{{ list_add + [item.apt | default(item.name)] }}"

- name: Apt install packages
  when:
    - list_add is defined
    - list_add | length > 0
  ansible.builtin.apt:
    name: "{{ list_add }}"
    state: "present"
    update_cache: "{{ packages_update_cache }}"
