---
- name: Dnf install updates
  register: dnf_result
  ansible.builtin.dnf:
    name: "*"
    update_cache: true
    state: latest

- name: Dnf get upgraded packages
  when: dnf_result.changed == "true"
  register: rpm_result
  args:
    warn: false
  ansible.builtin.shell:
    cmd: rpm -qa --last | grep "$(date +%a\ %d\ %b\ %Y)" | cut -f 1 -d " "

- name: Dnf show upgrades
  when: dnf_result.changed == "true"
  ansible.builtin.debug:
    msg: "{{ rpm_result.stdout_lines }}"
