---
- name: Yum install updates
  become: true
  register: yum_result
  ansible.builtin.yum:
    name: "*"
    update_cache: true
    state: latest

- name: Yum get upgraded packages
  become: true
  when: yum_result.changed
  register: rpm_result
  # args:
  #   warn: false
  ansible.builtin.shell:
    cmd: 'rpm -qa --last | grep "$(date +%a\ %d\ %b\ %Y)" | cut -f 1 -d " "'

- name: Yum show upgrades
  when: yum_result.changed
  ansible.builtin.debug:
    msg: "{{ rpm_result.stdout_lines }}"
