---
- name: Dnf install updates
  ansible.builtin.dnf:
    name: "*"
    update_cache: true
    state: latest
  register: dnf_result

- name: Dnf get upgraded packages
  ansible.builtin.shell:
    cmd: rpm -qa --last | grep "$(date +%a\ %d\ %b\ %Y)" | cut -f 1 -d " "
  register: rpm_result
  args:
    warn: false
  when: dnf_result.changed == "true"

- name: Dnf show upgrades
  ansible.builtin.debug:
    msg: "{{ rpm_result.stdout_lines }}"
  when: dnf_result.changed == "true"
