---
- name: Yum install updates
  ansible.builtin.yum:
    name: "*"
    update_cache: true
    state: latest
  register: yum_result

- name: Yum get upgraded packages
  ansible.builtin.shell:
    cmd: rpm -qa --last | grep "$(date +%a\ %d\ %b\ %Y)" | cut -f 1 -d " "
  register: rpm_result
  args:
    warn: false
  when: yum_result.changed == "true"

- name: Yum show upgrades
  ansible.builtin.debug:
    msg: "{{ rpm_result.stdout_lines }}"
  when: yum_result.changed == "true"
